# prometheus.yml
global:
  scrape_interval: 15s  # How frequently to scrape targets
  evaluation_interval: 15s  # How frequently to evaluate rules

scrape_configs:
  - job_name: 'ci-cd-pipeline'
    static_configs:
      - targets: ['localhost:8080']  # Replace with your application's address
